### ISSUE TITLE
Support EF from another project

### ISSUE THREAD

**Issue by tematim** [FranLsz/RepositoryPatternGenerator-VS-Extension#1]
Hello,

In my project there is the same edmx for API and WPF clients.

Is it possible to create the pattern with an external project with EDMX as the only files in it ?

Regards

**Comment by FranLsz** [comment]
Hi tematim,

Yes, its possible.

Your external project must have a folder named "Models" (for example) in the root of the project with EDMX file in it.

After that, click on Generate button located on Visual Studio menu and, in settings panel, put the name of that external project and the name of models" folder" with .edmx file.

Of course, you must have loaded the external project in the current solution to generate code.

Regards
